version: "3.9"

services:
  db:
    image: postgres:16
    container_name: loan_db
    restart: always
    environment:
      POSTGRES_DB: loan_db
      POSTGRES_USER: loan_user
      POSTGRES_PASSWORD: loan_pass
    ports:
      - "5432:5432"
    volumes:
      - loan_db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: loan_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/loan_db
      SPRING_DATASOURCE_USERNAME: loan_user
      SPRING_DATASOURCE_PASSWORD: loan_pass

volumes:
  loan_db_data: